module.exports = {
  YOU_HAVE_NOTHING: 'You have nothing to give.',
  GIVE_WHAT: 'Give what?',
  WITH_WHO: 'With whom?',
  THERE_IS_NOONE: 'There is no one here.',
  THEY_SAY_NOTHING: 'They say nothing.',
  TALK: 'Talk to',
  GIVE: 'Give something to',
  YOU_CANT_DROP: 'You can\'t drop that.',
  WHICH_ITEM: 'Which item?',
  NONE: '[None]',
  YOU_DROP: 'You drop',
  NOTHING_TO_EXAMINE: 'Nothing to examine',
  NOTHING_TO_TAKE: 'There\'s nothing to take.',
  YOU_CANT_TAKE: 'You can\'t take that.',
  YOU_ADD_1: 'You add',
  YOU_ADD_2: 'to your inventory.',
  NOTHING_TO_USE: 'Nothing to use',
  IT_DOES_NOTHING: 'Doesn\'t seem to do anything.',
  OPTION_STAY: 'Stay',
  YOU_CAN_GO: 'You can go',
  LOOK_AROUND: 'Look around',
  TAKE: 'Take',
  EXAMINE: 'Examine',
  GO: 'Go',
  DROP: 'Drop',
  USE: 'Use',
  INTERACT: 'Interact with',
  ITEM_HERE_1: 'There is',
  ITEM_HERE_2: 'here.'
};

